import React, { createContext, useContext, useState, ReactNode } from 'react';

export type LanguageCode = 'en' | 'sw' | 'es' | 'fr' | 'pt' | 'hi' | 'ja' | 'zh' | 'ru' | 'ar' | 'in';

export interface LanguageOption {
  code: LanguageCode;
  name: string;
  nativeName: string;
  flag: string;
}

export const LANGUAGES: LanguageOption[] = [
  { code: 'en', name: 'English', nativeName: 'English', flag: '🇬🇧' },
  { code: 'sw', name: 'Swahili', nativeName: 'Kiswahili', flag: '🇰🇪' },
  { code: 'es', name: 'Spanish', nativeName: 'Español', flag: '🇪🇸' },
  { code: 'fr', name: 'French', nativeName: 'Français', flag: '🇫🇷' },
  { code: 'pt', name: 'Portuguese', nativeName: 'Português', flag: '🇵🇹' },
  { code: 'hi', name: 'Hindi', nativeName: 'हिंदी', flag: '🇮🇳' },
  { code: 'ja', name: 'Japanese', nativeName: '日本語', flag: '🇯🇵' },
  { code: 'zh', name: 'Chinese Mandarin', nativeName: '中文 (普通话)', flag: '🇨🇳' },
  { code: 'ru', name: 'Russian', nativeName: 'Русский', flag: '🇷🇺' },
  { code: 'ar', name: 'Arabic', nativeName: 'العربية', flag: '🇦🇪' },
  { code: 'in', name: 'Indian Languages', nativeName: 'भारतीय (Regional)', flag: '🇮🇳' },
];

export const TRANSLATIONS: Record<LanguageCode, Record<string, string>> = {
  en: {
    navDestinations: 'Destinations',
    navPackages: 'Tour Packages',
    navServices: 'Our Services',
    navFaq: 'FAQ',
    navQuote: 'Custom Quote',
    topLicensed: 'Licensed Kenya Tour Operator',
    topServices: 'Passports • Visas • Ticketing • Safaris • Excursions',
    whatsappUs: 'WhatsApp Us',
    requestQuote: 'Request Quote',
    heroTag: 'Premier Kenya Safaris & Global Travel Consultancy',
    heroTitle: 'Premier Kenya Safaris & Global Travel Consultancy',
    heroSubtitle: 'Tailor-made, worry-free global travel itineraries and bespoke African wilderness expeditions curated for the discerning traveler.',
    searchPlaceholder: 'Search destinations (e.g. Maasai Mara, Diani, Dubai)...',
    searchButton: 'Search Safaris',
    exploreDestinations: 'Explore Premier Destinations',
    destinationsSubtitle: 'Handpicked safari parks, coastal beaches, and international getaways',
    filterAll: 'All Destinations',
    filterKenya: 'Kenya Safaris & Beaches',
    filterInternational: 'International Tours',
    startingFrom: 'Starting From',
    perPerson: 'per person',
    viewDetails: 'View Details',
    bookWhatsapp: 'Book via WhatsApp',
    exclusivePackages: 'Exclusive Tour Packages',
    packagesSubtitle: 'All-inclusive safari and vacation packages crafted for unforgettable experiences',
    inclusions: 'Package Highlights & Inclusions',
    inquirePackage: 'Inquire Package',
    viewFullPackage: 'View Full Itinerary',
    ourServices: 'Our Comprehensive Travel Services',
    servicesSubtitle: 'Full-service travel consultancy handling every step of your journey',
    customQuoteTitle: 'Build Your Custom Travel Itinerary',
    customQuoteSubtitle: 'Get an instant personalized safari estimate sent straight to your WhatsApp',
    faqTitle: 'Frequently Asked Questions',
    faqSubtitle: 'Everything you need to know about booking safaris and travel with Remax Safaris',
    footerAbout: 'Remax Safaris is a premier licensed Kenyan travel agency specializing in authentic wildlife safaris, beach holidays, visa processing, and global flight ticketing.',
    footerQuickLinks: 'Quick Links',
    footerContact: 'Contact Us',
    footerRights: 'All Rights Reserved. Remax Safaris Tours & Travel Consultancy.',
    languageSelect: 'Language',
  },
  sw: {
    navDestinations: 'Maweneo',
    navPackages: 'Vifurushi vya Ziara',
    navServices: 'Huduma Zetu',
    navFaq: 'Maswali',
    navQuote: 'Nukuu Maalum',
    topLicensed: 'Opereta Aliyeidhinishwa wa Utalii Kenya',
    topServices: 'Pasipoti • Visa • Tiketi • Safari • Reti',
    whatsappUs: 'Tutumie WhatsApp',
    requestQuote: 'Omba Nukuu',
    heroTag: 'Mshirika Wako Mkuu wa Safari na Utalii Kenya',
    heroTitle: 'Gundua Safari za Halisi za Kenya na Duniani',
    heroSubtitle: 'Safari maalum za wanyamapori, likizo za pwani, tiketi za ndege na usaidizi wa visa. Furahia matukio yasiyosahaulika.',
    searchPlaceholder: 'Tafuta maeneo (m.f. Maasai Mara, Diani, Dubai)...',
    searchButton: 'Tafuta Safari',
    exploreDestinations: 'Gundua Maeneo Makuu',
    destinationsSubtitle: 'Mbuga za wanyamapori zilizochaguliwa, fukwe za pwani na likizo za kimataifa',
    filterAll: 'Maeneo Yote',
    filterKenya: 'Safari na Fukwe za Kenya',
    filterInternational: 'Ziara za Kimataifa',
    startingFrom: 'Anzia',
    perPerson: 'kwa mtu',
    viewDetails: 'Angalia Maelezo',
    bookWhatsapp: 'Weka Kitabu WhatsApp',
    exclusivePackages: 'Vifurushi Maalum vya Ziara',
    packagesSubtitle: 'Vifurushi kamili vya safari na likizo vilivyoundwa kwa matukio yasiyosahaulika',
    inclusions: 'Mambo Muhimu na Vilivyomo',
    inquirePackage: 'Uliza Kuhusu Kifurushi',
    viewFullPackage: 'Onyesha Ratiba Kamili',
    ourServices: 'Huduma Zetu za Usafiri',
    servicesSubtitle: 'Ushauri kamili wa usafiri unaoshughulikia kila hatua ya safari yako',
    customQuoteTitle: 'Unda Ratiba Yako Maalum ya Usafiri',
    customQuoteSubtitle: 'Pata makadirio ya safari yaliyogeuzwa kukufaa yakitumwa kwenye WhatsApp yako',
    faqTitle: 'Maswali Yanayoulizwa Mara kwa Mara',
    faqSubtitle: 'Kila kitu unachohitaji kujua kuhusu kuweka nafasi ya safari na Remax Safaris',
    footerAbout: 'Remax Safaris ni shirika kuu la usafiri lililoidhinishwa nchini Kenya linalobobea katika safari za wanyamapori, likizo za pwani, visa na tiketi.',
    footerQuickLinks: 'Viungo vya Haraka',
    footerContact: 'Mawasiliano',
    footerRights: 'Haki Zote Zimehifadhiwa. Remax Safaris Tours & Travel Consultancy.',
    languageSelect: 'Lugha',
  },
  es: {
    navDestinations: 'Destinos',
    navPackages: 'Paquetes de Viaje',
    navServices: 'Servicios',
    navFaq: 'Preguntas',
    navQuote: 'Cotización',
    topLicensed: 'Operador Turístico Licenciado en Kenia',
    topServices: 'Pasaportes • Visados • Billetes • Safaris • Excursiones',
    whatsappUs: 'WhatsApp',
    requestQuote: 'Solicitar Cotización',
    heroTag: 'Su Socio Principal de Safaris y Viajes en Kenia',
    heroTitle: 'Descubra Safaris Auténticos en Kenia y el Mundo',
    heroSubtitle: 'Safaris personalizados, vacaciones de playa, billetes de avión y visados. Experimente aventuras inolvidables.',
    searchPlaceholder: 'Buscar destinos (ej. Maasai Mara, Diani, Dubái)...',
    searchButton: 'Buscar Safaris',
    exploreDestinations: 'Explore Destinos Principales',
    destinationsSubtitle: 'Parques nacionales, playas costeras y escapadas internacionales',
    filterAll: 'Todos los Destinos',
    filterKenya: 'Safaris y Playas de Kenia',
    filterInternational: 'Tours Internacionales',
    startingFrom: 'Desde',
    perPerson: 'por persona',
    viewDetails: 'Ver Detalles',
    bookWhatsapp: 'Reservar por WhatsApp',
    exclusivePackages: 'Paquetes Exclusivos',
    packagesSubtitle: 'Paquetes todo incluido diseñados para experiencias inolvidables',
    inclusions: 'Lo Más Destacado del Paquete',
    inquirePackage: 'Consultar Paquete',
    viewFullPackage: 'Ver Itinerario Completo',
    ourServices: 'Nuestros Servicios de Viaje',
    servicesSubtitle: 'Consultoría integral de viajes para cada paso de su aventura',
    customQuoteTitle: 'Cree su Itinerario Personalizado',
    customQuoteSubtitle: 'Reciba una cotización personalizada directamente en su WhatsApp',
    faqTitle: 'Preguntas Frecuentes',
    faqSubtitle: 'Todo lo que necesita saber sobre safaris con Remax Safaris',
    footerAbout: 'Remax Safaris es una agencia de viajes con licencia en Kenia especializada en safaris auténticos, vacaciones de playa y visados.',
    footerQuickLinks: 'Enlaces Rápidos',
    footerContact: 'Contacto',
    footerRights: 'Todos los derechos reservados. Remax Safaris Tours & Travel.',
    languageSelect: 'Idioma',
  },
  fr: {
    navDestinations: 'Destinations',
    navPackages: 'Circuits & Forfaits',
    navServices: 'Nos Services',
    navFaq: 'FAQ',
    navQuote: 'Devis Sur Mesure',
    topLicensed: 'Opérateur Touristique Agréé au Kenya',
    topServices: 'Passeports • Visas • Billetterie • Safaris • Excursions',
    whatsappUs: 'Contact WhatsApp',
    requestQuote: 'Demander un Devis',
    heroTag: 'Votre Partenaire Safari et Voyage Privilégié au Kenya',
    heroTitle: 'Découvrez des Safaris Authentiques au Kenya & dans le Monde',
    heroSubtitle: 'Safaris sur mesure, séjours côtiers, billetterie aérienne et assistance visa. Vivez des aventures inoubliables.',
    searchPlaceholder: 'Rechercher une destination (ex. Maasai Mara, Diani, Dubaï)...',
    searchButton: 'Rechercher',
    exploreDestinations: 'Explorez nos Meilleures Destinations',
    destinationsSubtitle: 'Parcs nationaux, plages tropicales et escapades internationales',
    filterAll: 'Toutes les Destinations',
    filterKenya: 'Safaris & Plages au Kenya',
    filterInternational: 'Tours Internationaux',
    startingFrom: 'À partir de',
    perPerson: 'par personne',
    viewDetails: 'Voir Détails',
    bookWhatsapp: 'Réserver via WhatsApp',
    exclusivePackages: 'Forfaits Exclusifs',
    packagesSubtitle: 'Circuits tout compris conçus pour des souvenirs inoubliables',
    inclusions: 'Points Forts du Forfait',
    inquirePackage: 'Demander des Infos',
    viewFullPackage: 'Voir l\'Itinéraire',
    ourServices: 'Nos Services de Voyage',
    servicesSubtitle: 'Agence de voyage complète vous accompagnant à chaque étape',
    customQuoteTitle: 'Créez votre Itinéraire Personnalisé',
    customQuoteSubtitle: 'Obtenez un devis sur mesure envoyé directement sur votre WhatsApp',
    faqTitle: 'Foire Aux Questions',
    faqSubtitle: 'Tout ce que vous devez savoir pour réserver avec Remax Safaris',
    footerAbout: 'Remax Safaris est une agence kenyane agréée spécialisée dans les safaris, les séjours balnéaires, la billetterie et les visas.',
    footerQuickLinks: 'Liens Rapides',
    footerContact: 'Contactez-nous',
    footerRights: 'Tous droits réservés. Remax Safaris Tours & Travel Consultancy.',
    languageSelect: 'Langue',
  },
  pt: {
    navDestinations: 'Destinos',
    navPackages: 'Pacotes de Viagem',
    navServices: 'Serviços',
    navFaq: 'Perguntas',
    navQuote: 'Cotação',
    topLicensed: 'Operador Turístico Licenciado no Quênia',
    topServices: 'Passaportes • Visados • Passagens • Safáris • Excursões',
    whatsappUs: 'Fale no WhatsApp',
    requestQuote: 'Pedir Cotação',
    heroTag: 'Seu Parceiro Principal de Safáris e Viagens no Quênia',
    heroTitle: 'Descubra Safáris Autênticos no Quênia e no Mundo',
    heroSubtitle: 'Safáris personalizados, praias tropicais, passagens aéreas e vistos. Viva experiências inesquecíveis.',
    searchPlaceholder: 'Buscar destinos (ex: Maasai Mara, Diani, Dubai)...',
    searchButton: 'Buscar Safáris',
    exploreDestinations: 'Explore Principais Destinos',
    destinationsSubtitle: 'Parques de vida selvagem, praias e viagens internacionais',
    filterAll: 'Todos os Destinos',
    filterKenya: 'Safáris e Praias no Quênia',
    filterInternational: 'Tours Internacionais',
    startingFrom: 'A partir de',
    perPerson: 'por pessoa',
    viewDetails: 'Ver Detalhes',
    bookWhatsapp: 'Reservar no WhatsApp',
    exclusivePackages: 'Pacotes Exclusivos',
    packagesSubtitle: 'Pacotes com tudo incluído criados para experiências inesquecíveis',
    inclusions: 'Destaques do Pacote',
    inquirePackage: 'Consultar Pacote',
    viewFullPackage: 'Ver Roteiro Completo',
    ourServices: 'Nossos Serviços de Viagem',
    servicesSubtitle: 'Consultoria completa cobrindo cada etapa da sua viagem',
    customQuoteTitle: 'Monte seu Roteiro Personalizado',
    customQuoteSubtitle: 'Receba uma estimativa personalizada direto no seu WhatsApp',
    faqTitle: 'Perguntas Frequentes',
    faqSubtitle: 'Tudo o que você precisa saber sobre reservar com a Remax Safaris',
    footerAbout: 'A Remax Safaris é uma agência de viagens licenciada no Quênia especializada em safáris, férias na praia, passagens e vistos.',
    footerQuickLinks: 'Links Rápidos',
    footerContact: 'Contato',
    footerRights: 'Todos os direitos reservados. Remax Safaris Tours & Travel.',
    languageSelect: 'Idioma',
  },
  hi: {
    navDestinations: 'गंतव्य',
    navPackages: 'टूर पैकेज',
    navServices: 'हमारी सेवाएं',
    navFaq: 'प्रश्न',
    navQuote: 'कस्टम कोटेशन',
    topLicensed: 'केन्या लाइसेंस प्राप्त टूर ऑपरेटर',
    topServices: 'पासपोर्ट • वीजा • टिकटिंग • सफारी • पर्यटन',
    whatsappUs: 'व्हाट्सएप करें',
    requestQuote: 'कोटेशन प्राप्त करें',
    heroTag: 'केन्या में आपका प्रमुख सफारी और यात्रा भागीदार',
    heroTitle: 'केन्या और दुनिया भर में प्रामाणिक सफारी की खोज करें',
    heroSubtitle: 'व्यक्तिगत वन्यजीव सफारी, उष्णकटिबंधीय समुद्र तट की छुट्टियां, फ्लाइट टिकटिंग और वीजा सहायता।',
    searchPlaceholder: 'गंतव्य खोजें (जैसे मसाई मारा, दियानी, दुबई)...',
    searchButton: 'सफारी खोजें',
    exploreDestinations: 'प्रमुख गंतव्यों का अन्वेषण करें',
    destinationsSubtitle: 'चुनिंदा राष्ट्रीय उद्यान, समुद्र तट और अंतरराष्ट्रीय पर्यटन',
    filterAll: 'सभी गंतव्य',
    filterKenya: 'केन्या सफारी और समुद्र तट',
    filterInternational: 'अंतरराष्ट्रीय टूर',
    startingFrom: 'प्रारंभिक मूल्य',
    perPerson: 'प्रति व्यक्ति',
    viewDetails: 'विवरण देखें',
    bookWhatsapp: 'व्हाट्सएप पर बुक करें',
    exclusivePackages: 'विशेष टूर पैकेज',
    packagesSubtitle: 'अविस्मरणीय अनुभवों के लिए निर्मित ऑल-इनक्लूसिव टूर पैकेज',
    inclusions: 'पैकेज की मुख्य विशेषताएं',
    inquirePackage: 'पैकेज के बारे में पूछें',
    viewFullPackage: 'पूरा यात्रा कार्यक्रम देखें',
    ourServices: 'हमारी यात्रा सेवाएं',
    servicesSubtitle: 'आपकी यात्रा के हर कदम को संभालने वाली पूर्ण यात्रा परामर्श',
    customQuoteTitle: 'अपनी कस्टम यात्रा योजना बनाएं',
    customQuoteSubtitle: 'सीधे अपने व्हाट्सएप पर व्यक्तिगत सफारी अनुमान प्राप्त करें',
    faqTitle: 'अक्सर पूछे जाने वाले प्रश्न',
    faqSubtitle: 'रेमैक्स सफारी के साथ बुकिंग के बारे में सब कुछ जानें',
    footerAbout: 'रेमैक्स सफारी केन्या की एक प्रमुख लाइसेंस प्राप्त ट्रैवल एजेंसी है जो वन्यजीव सफारी, समुद्र तट की छुट्टियों और वीजा सहायता में विशेषज्ञता रखती है।',
    footerQuickLinks: 'त्वरित लिंक',
    footerContact: 'संपर्क करें',
    footerRights: 'सर्वाधिकार सुरक्षित। रेमैक्स सफारिस टूर्स एंड ट्रैवल।',
    languageSelect: 'भाषा',
  },
  ja: {
    navDestinations: '目的地',
    navPackages: 'ツアーパッケージ',
    navServices: 'サービス内容',
    navFaq: 'よくある質問',
    navQuote: '見積もり依頼',
    topLicensed: 'ケニア政府公認ツアーオペレーター',
    topServices: 'パスポート • ビザ手配 • 航空券 • サファリ • オプショナルツアー',
    whatsappUs: 'WhatsAppでお問い合わせ',
    requestQuote: '見積もりを請求',
    heroTag: 'ケニアで最も信頼されるサファリ＆トラベルパートナー',
    heroTitle: 'ケニアと世界を結ぶ本物のサファリ体験',
    heroSubtitle: 'オーダーメイドの野生動物サファリ、リゾートビーチ、航空券手配、ビザサポート。忘れられない冒険をお届けします。',
    searchPlaceholder: '目的地を検索 (マサイマラ、ディアンニ、ドバイなど)...',
    searchButton: 'サファリを検索',
    exploreDestinations: '人気の目的地を探す',
    destinationsSubtitle: '厳選された国立公園、美しいビーチ、海外のリゾート地',
    filterAll: 'すべての目的地',
    filterKenya: 'ケニアサファリ＆ビーチ',
    filterInternational: '海外ツアー',
    startingFrom: '最安料金',
    perPerson: 'お一人様あたり',
    viewDetails: '詳細を見る',
    bookWhatsapp: 'WhatsAppで予約',
    exclusivePackages: 'おすすめパッケージツアー',
    packagesSubtitle: '充実のオールインクルーシブプランで最高の旅を演出',
    inclusions: 'ハイライト＆含まれるもの',
    inquirePackage: 'プランについて相談',
    viewFullPackage: '全日程を見る',
    ourServices: '総合トラベルサービス',
    servicesSubtitle: 'ご旅行の準備からご帰国まで手厚くサポート',
    customQuoteTitle: 'カスタム旅程の作成',
    customQuoteSubtitle: 'あなただけのサファリ見積もりをWhatsAppに即座にお届け',
    faqTitle: 'よくある質問 (FAQ)',
    faqSubtitle: 'Remax Safarisのご予約に関する不明点はこちら',
    footerAbout: 'Remax Safarisは、野生動物サファリ、ビーチリゾート、ビザ・航空券手配を専門とするケニア政府公認の旅行会社です。',
    footerQuickLinks: 'クイックリンク',
    footerContact: 'お問い合わせ',
    footerRights: 'All Rights Reserved. Remax Safaris Tours & Travel.',
    languageSelect: '言語',
  },
  zh: {
    navDestinations: '目的地',
    navPackages: '旅游套餐',
    navServices: '我们的服务',
    navFaq: '常见问题',
    navQuote: '定制报价',
    topLicensed: '肯尼亚官方持牌旅行社 Operator',
    topServices: '护照 • 签证办理 • 机票预订 • 游猎游 • 观光游',
    whatsappUs: 'WhatsApp 联系',
    requestQuote: '索取报价',
    heroTag: '您在肯尼亚的首选野生动物游猎与旅行合作伙伴',
    heroTitle: '探索肯尼亚与全球的纯正 Safari 探索之旅',
    heroSubtitle: '量身定制的野生动物游猎、热带海滩度假、国际机票预订与签证协助，开启难忘之旅。',
    searchPlaceholder: '搜索目的地 (例如: 马赛马拉, 迪阿尼, 迪拜)...',
    searchButton: '搜索 Safari',
    exploreDestinations: '探索精选目的地',
    destinationsSubtitle: '精选野生动物公园、海滨度假胜地与国际旅游路线',
    filterAll: '全部目的地',
    filterKenya: '肯尼亚游猎与海滩',
    filterInternational: '国际旅游',
    startingFrom: '起价',
    perPerson: '每人',
    viewDetails: '查看详情',
    bookWhatsapp: '通过 WhatsApp 预订',
    exclusivePackages: '尊享套餐',
    packagesSubtitle: '全包式 Safari 与度假套餐，打造终生难忘体验',
    inclusions: '套餐亮点与包含项目',
    inquirePackage: '咨询此套餐',
    viewFullPackage: '查看完整行程',
    ourServices: '全方位旅行服务',
    servicesSubtitle: '专业一站式旅行咨询，贴心服务每一程',
    customQuoteTitle: '定制您的专属旅行行程',
    customQuoteSubtitle: '立即通过 WhatsApp 获取个性化游猎报价',
    faqTitle: '常见问题解答',
    faqSubtitle: '关于预订 Remax Safaris 旅行的解答',
    footerAbout: 'Remax Safaris 是肯尼亚持牌旅行机构，专注于野生动物 Safari、海滩假期、机票与签证办理服务。',
    footerQuickLinks: '快速链接',
    footerContact: '联系我们',
    footerRights: '版权所有。Remax Safaris Tours & Travel Consultancy。',
    languageSelect: '语言',
  },
  ru: {
    navDestinations: 'Направления',
    navPackages: 'Турпакеты',
    navServices: 'Наши Услуги',
    navFaq: 'Частые Вопросы',
    navQuote: 'Запросить Расчет',
    topLicensed: 'Лицензированный Туроператор в Кении',
    topServices: 'Паспорта • Визы • Авиабилеты • Сафари • Экскурсии',
    whatsappUs: 'Написать в WhatsApp',
    requestQuote: 'Получить Расчет',
    heroTag: 'Ваш Главный Партнер по Сафари и Путешествиям в Кении',
    heroTitle: 'Откройте для Себя Настоящие Сафари в Кении и по Всему Миру',
    heroSubtitle: 'Индивидуальные сафари, пляжный отдых, авиабилеты и визовая поддержка.',
    searchPlaceholder: 'Поиск направлений (например, Масаи Мара, Диани, Дубай)...',
    searchButton: 'Найти Сафари',
    exploreDestinations: 'Исследуйте Лучшие Направления',
    destinationsSubtitle: 'Национальные парки, тропические пляжи и международные туры',
    filterAll: 'Все Направления',
    filterKenya: 'Сафари и Пляжи Кении',
    filterInternational: 'Международные Туры',
    startingFrom: 'От',
    perPerson: 'за человека',
    viewDetails: 'Подробнее',
    bookWhatsapp: 'Забронировать в WhatsApp',
    exclusivePackages: 'Эксклюзивные Турпакеты',
    packagesSubtitle: 'Всё включено для незабываемых впечатлений',
    inclusions: 'Включено в Стоимость',
    inquirePackage: 'Узнать Подробнее',
    viewFullPackage: 'Полная Программа',
    ourServices: 'Наши Туристические Услуги',
    servicesSubtitle: 'Полный спектр услуг от бронирования до сопровождения',
    customQuoteTitle: 'Создайте Свой Индивидуальный Маршрут',
    customQuoteSubtitle: 'Получите персональный расчет прямо в WhatsApp',
    faqTitle: 'Часто Задаваемые Вопросы',
    faqSubtitle: 'Всё, что нужно знать о бронировании туров с Remax Safaris',
    footerAbout: 'Remax Safaris — лицензированное туроператорское агентство в Кении, специализирующееся на сафари, пляжном отдыхе и визах.',
    footerQuickLinks: 'Быстрые Ссылки',
    footerContact: 'Контакты',
    footerRights: 'Все права защищены. Remax Safaris Tours & Travel.',
    languageSelect: 'Язык',
  },
  ar: {
    navDestinations: 'الوجهات',
    navPackages: 'باقات الرحلات',
    navServices: 'خدماتنا',
    navFaq: 'الأسئلة الشائعة',
    navQuote: 'عرض سعر خاص',
    topLicensed: 'مرخص رسميًا كمنظم رحلات في كينيا',
    topServices: 'جوازات سفر • تأشيرات • تذاكر طيران • سفاري • رحلات',
    whatsappUs: 'تواصل عبر واتساب',
    requestQuote: 'طلب عرض سعر',
    heroTag: 'شريكك الأول لرحلات السفاري والسفر في كينيا',
    heroTitle: 'اكتشف رحلات السفاري الأصيلة في كينيا وحول العالم',
    heroSubtitle: 'رحلات سفاري مخصصة للحيوانات البرية، عطلات شاطئية استوائية، حجز تذاكر الطيران، ومساعدة التأشيرات.',
    searchPlaceholder: 'ابحث عن وجهة (مثل ماساي مارا، دياني، دبي)...',
    searchButton: 'بحث عن سفاري',
    exploreDestinations: 'استكشف أفضل الوجهات',
    destinationsSubtitle: 'محميات برية مختارة، شواطئ ساحلية، ورحلات دولية مميزة',
    filterAll: 'جميع الوجهات',
    filterKenya: 'سفاري وشواطئ كينيا',
    filterInternational: 'رحلات دولية',
    startingFrom: 'تبدأ من',
    perPerson: 'للشخص الواحد',
    viewDetails: 'عرض التفاصيل',
    bookWhatsapp: 'الحجز عبر واتساب',
    exclusivePackages: 'باقات رحلات حصرية',
    packagesSubtitle: 'باقات شاملة لجميع الخدمات صممت لتجارب لا تُنسى',
    inclusions: 'أبرز مميزات الباقة',
    inquirePackage: 'الاستفسار عن الباقة',
    viewFullPackage: 'عرض البرنامج الكامل',
    ourServices: 'خدمات السفر الشاملة',
    servicesSubtitle: 'استشارات سفر متكاملة تلبي كافة احتياجات رحلتك',
    customQuoteTitle: 'صمم برنامج رحلتك الخاص',
    customQuoteSubtitle: 'احصل على تقدير مخصص لرحلتك مرسل مباشرة إلى واتساب',
    faqTitle: 'الأسئلة الأكثر تكراراً',
    faqSubtitle: 'كل ما تحتاج معرفته عن الحجز مع ريماكس سفاري',
    footerAbout: 'ريماكس سفاري هي وكالة سفر كينية مرخصة متخصصة في رحلات السفاري البرية، العطلات الشاطئية، التأشيرات وتذاكر الطيران.',
    footerQuickLinks: 'روابط سريعة',
    footerContact: 'اتصل بنا',
    footerRights: 'جميع الحقوق محفوظة. ريماكس سفاري للسياحة والسفر.',
    languageSelect: 'اللغة',
  },
  in: {
    navDestinations: 'गंतव्य / Destinations',
    navPackages: 'टूर पैकेज / Packages',
    navServices: 'सेवाएं / Services',
    navFaq: 'प्रश्न / FAQ',
    navQuote: 'कस्टम कोटेशन',
    topLicensed: 'केन्या सरकार द्वारा मान्यता प्राप्त टूर ऑपरेटर',
    topServices: 'पासपोर्ट • वीजा सहायता • हवाई टिकट • सफारी • पर्यटन',
    whatsappUs: 'व्हाट्सएप करें',
    requestQuote: 'कोटेशन प्राप्त करें',
    heroTag: 'केन्या में आपका विश्वसनीय सफारी और यात्रा भागीदार',
    heroTitle: 'केन्या और विश्व की अद्भुत यात्राओं का आनंद लें',
    heroSubtitle: 'कस्टम सफारी, समुद्र तट की छुट्टियां, उड़ान टिकट और वीजा सहायता।',
    searchPlaceholder: 'गंतव्य खोजें (मासाई मारा, दियानी, दुबई)...',
    searchButton: 'सफारी खोजें',
    exploreDestinations: 'सर्वश्रेष्ठ यात्रा स्थल',
    destinationsSubtitle: 'वन्यजीव अभयारण्य, समुद्र तट और अंतरराष्ट्रीय पर्यटन स्थल',
    filterAll: 'सभी गंतव्य',
    filterKenya: 'केन्या सफारी और तट',
    filterInternational: 'अंतरराष्ट्रीय पर्यटन',
    startingFrom: 'प्रारंभिक मूल्य',
    perPerson: 'प्रति व्यक्ति',
    viewDetails: 'विवरण देखें',
    bookWhatsapp: 'व्हाट्सएप पर बुक करें',
    exclusivePackages: 'विशेष टूर पैकेज',
    packagesSubtitle: 'अविस्मरणीय अनुभवों के लिए सर्व-समावेशी टूर पैकेज',
    inclusions: 'मुख्य आकर्षण और शामिल सेवाएं',
    inquirePackage: 'जानकारी प्राप्त करें',
    viewFullPackage: 'पूरा यात्रा विवरण',
    ourServices: 'हमारी यात्रा सेवाएं',
    servicesSubtitle: 'आपकी सुखद यात्रा के लिए संपूर्ण यात्रा समाधान',
    customQuoteTitle: 'अपनी मनपसंद यात्रा योजना बनाएं',
    customQuoteSubtitle: 'व्हाट्सएप पर तुरंत व्यक्तिगत टूर अनुमान प्राप्त करें',
    faqTitle: 'अक्सर पूछे जाने वाले प्रश्न',
    faqSubtitle: 'बुकिंग और यात्रा से संबंधित संपूर्ण जानकारी',
    footerAbout: 'रेमैक्स सफारिस केन्या की प्रमुख टूर और ट्रैवल एजेंसी है जो सफारी और यात्रा में विशेषज्ञ है।',
    footerQuickLinks: 'त्वरित लिंक',
    footerContact: 'संपर्क करें',
    footerRights: 'सर्वाधिकार सुरक्षित। रेमैक्स सफारिस टूर्स एंड ट्रैवल।',
    languageSelect: 'भाषा / Language',
  },
};

interface LanguageContextType {
  language: LanguageCode;
  setLanguage: (lang: LanguageCode) => void;
  t: (key: string) => string;
  currentLanguageObj: LanguageOption;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<LanguageCode>('en');

  const t = (key: string): string => {
    return TRANSLATIONS[language]?.[key] || TRANSLATIONS.en[key] || key;
  };

  const currentLanguageObj = LANGUAGES.find((l) => l.code === language) || LANGUAGES[0];

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, currentLanguageObj }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
